services:
  word-engine:
    build: ./word-engine/
    command: "python app.py"
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    networks:
      - my-network

  game-service:
    build: ./game-service/
    command: "java -jar app.jar"
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend-react:
    build:
      context: ./frontend-react/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  # Define a custom network
  my-network:
    driver: bridge
